global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:


scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Application
  - job_name: 'project-tracker-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['project-tracker-app:8080']
    scrape_timeout: 10s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
        - targets: ['redis-exporter:9121']